In [1]:
# import packages
import pandas as pd

## Load Data

In [6]:
data = pd.read_csv("dataset/final_df.csv")

data.head()

,Order Date,Purchase Price Per Unit,Quantity,Shipping Address State,Title,ASIN/ISBN (Product Code),Survey ResponseID,Category
0,2018-12-04,7.98,1,NJ,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,B0143RTB1E,R_01vNIayewjIIKMF,Electronics
1,2018-12-22,13.99,1,NJ,Betron BS10 Earphones Wired Headphones in Ear ...,B01MA1MJ6H,R_01vNIayewjIIKMF,Electronics
2,2018-12-24,8.99,1,NJ,NaN,B078JZTFN3,R_01vNIayewjIIKMF,NaN
3,2018-12-25,10.45,1,NJ,Perfecto Stainless Steel Shaving Bowl. Durable...,B06XWF9HML,R_01vNIayewjIIKMF,Kitchen & Dining
4,2018-12-25,10.00,1,NJ,Proraso Shaving Cream for Men,B00837ZOI0,R_01vNIayewjIIKMF,Beauty & Personal Care

## Clean Data

In [7]:
# drop unnecessary columns
df = data.drop(columns=["Order Date", "Shipping Address State", "Survey ResponseID"])

# remove null / NA values
df = df.dropna()

df

,Purchase Price Per Unit,Quantity,Title,ASIN/ISBN (Product Code),Category
0,7.98,1,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,B0143RTB1E,Electronics
1,13.99,1,Betron BS10 Earphones Wired Headphones in Ear ...,B01MA1MJ6H,Electronics
3,10.45,1,Perfecto Stainless Steel Shaving Bowl. Durable...,B06XWF9HML,Kitchen & Dining
4,10.00,1,Proraso Shaving Cream for Men,B00837ZOI0,Beauty & Personal Care
5,10.99,1,Micro USB Cable Android Charger - Syncwire [2-...,B01GFB2E9M,Computer & Accessories
...,...,...,...,...,...
1392015,6.99,1,Tanner's Tasty Paste Vanilla Bling - Anticavit...,B015ZRTHVA,"Health, Household & Personal Care"
1392016,15.99,1,Sinland Microfiber Cleaning Cloth Dish Cloth K...,B00QGCXPRG,"Health, Household & Personal Care"
1392017,6.99,4,Tanner's Tasty Paste Vanilla Bling - Anticavit...,B015ZRTHVA,"Health, Household & Personal Care"
1392018,6.99,4,Tanner's Tasty Paste Vanilla Bling - Anticavit...,B015ZRTHVA,"Health, Household & Personal Care"
1392019,19.99,1,Wild Mystic Oracle Card Deck: A 50-Card Deck a...,1441337652,Books

## Data Preprocessing

In [8]:
# finding the most common item in order to compare for competition
from collections import Counter 
import nltk

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# to remove stopwords and symbols and numbers
def is_valid_word(word):
    return word.isalpha() and len(word) >= 3

# split title into list of words
df_split_title = df["Title"].str.split()

# define noun tags
NOUN_TAGS = {"NN", "NNS", "NNP", "NNPS"}

# process each title to extract nouns without modifying the original df
nouns_count = Counter(
    word 
    for title in df_split_title
    for word, pos in nltk.pos_tag(title)  # POS tag each word in each title
    if is_valid_word(word) and pos in NOUN_TAGS  # keep only nouns
)

nouns_count

[nltk_data] Downloading package punkt to /Users/raisie/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/raisie/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Counter({'Pack': 86249,
         'Black': 65305,
         'Count': 57772,
         'Set': 53579,
         'Women': 49854,
         'Ounce': 49240,
         'Hair': 42933,
         'Gift': 42417,
         'Card': 40799,
         'Free': 39532,
         'White': 39414,
         'Dog': 39117,
         'Amazon': 38509,
         'Kids': 38448,
         'Cat': 37872,
         'Case': 37738,
         'Natural': 34630,
         'USB': 34032,
         'Soft': 33421,
         'Bag': 32285,
         'Water': 30940,
         'Baby': 30818,
         'Compatible': 30282,
         'Home': 29339,
         'Size': 28873,
         'iPhone': 28314,
         'Men': 28222,
         'Light': 28150,
         'Steel': 28098,
         'High': 27035,
         'Kit': 26673,
         'Food': 26205,
         'Cover': 26169,
         'Large': 25877,
         'Organic': 25412,
         'Cable': 25196,
         'Dry': 24759,
         'Premium': 24202,
         'Stainless': 23733,
         'Inch': 23707,
         'Storage': 23602,
         'Long': 23417,
         'Face': 23309,
         'Blue': 22523,
         'Skin': 22449,
         'Wall': 22177,
         'Box': 22042,
         'Oil': 21939,
         'Replacement': 21839,
         'Pro': 21802,
         'Small': 21412,
         'Easy': 21361,
         'Mini': 21187,
         'Body': 20648,
         'LED': 20484,
         'Ultra': 20084,
         'Kitchen': 19873,
         'Cotton': 19860,
         'Air': 19849,
         'Support': 19771,
         'Power': 19688,
         'Holder': 19296,
         'Glass': 19265,
         'Party': 19193,
         'Car': 19102,
         'Pet': 18689,
         'Gluten': 18629,
         'Original': 18608,
         'Color': 18420,
         'Girls': 18394,
         'Waterproof': 18316,
         'Outdoor': 18192,
         'All': 17997,
         'Adjustable': 17916,
         'Coffee': 17831,
         'Nail': 17736,
         'Silicone': 17545,
         'Vitamin': 17528,
         'Travel': 17370,
         'Sleeve': 17074,
         'Plastic': 16916,
         'May': 16899,
         'Clear': 16895,
         'Screen': 16805,
         'Paper': 16410,
         'Heavy': 16380,
         'Wireless': 16325,
         'Portable': 16268,
         'Brand': 16129,
         'Galaxy': 16070,
         'Extra': 16043,
         'Gel': 15899,
         'Phone': 15596,
         'Toy': 15494,
         'Protector': 15405,
         'Bags': 15322,
         'Full': 15282,
         'Metal': 15144,
         'Brush': 14926,
         'Medium': 14925,
         'Adapter': 14912,
         'Protein': 14896,
         'Apple': 14873,
         'Toys': 14535,
         'Basics': 14518,
         'Battery': 14503,
         'Care': 14455,
         'Super': 14445,
         'Charger': 14354,
         'Bottle': 14335,
         'Office': 14263,
         'Plus': 14139,
         'Foods': 13924,
         'Made': 13853,
         'Powder': 13786,
         'Classic': 13672,
         'Duty': 13540,
         'Supplement': 13539,
         'Christmas': 13535,
         'Reload': 13506,
         'Fit': 13401,
         'Indoor': 13292,
         'Tea': 13287,
         'Game': 13278,
         'Shower': 13233,
         'Protection': 13227,
         'Series': 13147,
         'Variety': 13125,
         'Samsung': 13048,
         'Balance': 12894,
         'Liquid': 12854,
         'Gold': 12819,
         'Relief': 12678,
         'Red': 12575,
         'Organizer': 12570,
         'Double': 12356,
         'Low': 12346,
         'Adult': 12319,
         'Cleaning': 12307,
         'Gifts': 12158,
         'Top': 12152,
         'Cream': 12144,
         'Stand': 12132,
         'Chicken': 12031,
         'Cord': 12024,
         'Control': 11825,
         'Green': 11809,
         'Chocolate': 11773,
         'Smart': 11701,
         'Dogs': 11694,
         'Dark': 11644,
         'Charging': 11589,
         'Hand': 11588,
         'Short': 11518,
         'Bed': 11489,
         'Back': 11424,
         'Tool': 11413,
         'Neck': 11404,
         'Art': 11397,
         'Accessories': 11341,
         'Electric': 11274,
         'New': 11215,
         'Leather': 11129,
         'Capsules': 11123,
         'Perfect': 11097,
         'Filter': 10891,
         'Lights': 10855,
         'Vegan': 10818,
         'Dress': 10792,
         'Birthday': 10744,
         'Fast': 10733,
         'Casual': 10730,
         'Piece': 10703,
         'Lightweight': 10690,
         'Foam': 10658,
         'Silver': 10658,
         'Bath': 10600,
         'Fruit': 10580,
         'Socks': 10570,
         'Colors': 10496,
         'Pure': 10477,
         'Book': 10476,
         'Day': 10423,
         'Boys': 10378,
         'Wet': 10363,
         'Wood': 10344,
         'Pillow': 10335,
         'DIY': 10215,
         'Mask': 10179,
         'Hard': 10171,
         'Health': 10102,
         'Sugar': 10097,
         'Adults': 9924,
         'Energy': 9910,
         'Cleaner': 9850,
         'Sheets': 9845,
         'Fresh': 9827,
         'Great': 9762,
         'Memory': 9759,
         'Dual': 9745,
         'Hot': 9744,
         'Round': 9695,
         'Healthy': 9685,
         'Spray': 9675,
         'Bathroom': 9651,
         'inch': 9648,
         'Eye': 9626,
         'Pad': 9611,
         'Pocket': 9561,
         'Bluetooth': 9530,
         'Digital': 9525,
         'Slim': 9517,
         'Non': 9506,
         'Switch': 9478,
         'Design': 9470,
         'Sports': 9450,
         'Protective': 9435,
         'Professional': 9431,
         'USA': 9424,
         'Laptop': 9344,
         'Pieces': 9297,
         'Garden': 9292,
         'Makeup': 9172,
         'Reusable': 9131,
         'Plant': 9120,
         'Clean': 9024,
         'Pain': 9021,
         'Mat': 9005,
         'Toilet': 8964,
         'Hanging': 8953,
         'Safe': 8894,
         'Door': 8869,
         'Standard': 8773,
         'Ear': 8760,
         'Pink': 8707,
         'Deep': 8705,
         'Assorted': 8693,
         'Fabric': 8640,
         'Pads': 8634,
         'Immune': 8617,
         'Desk': 8616,
         'Daily': 8614,
         'Jewelry': 8595,
         'Cup': 8581,
         'Certified': 8573,
         'Mount': 8562,
         'Womens': 8529,
         'Strength': 8499,
         'Nintendo': 8443,
         'Snack': 8430,
         'Decor': 8385,
         'Facial': 8344,
         'Computer': 8342,
         'Ring': 8260,
         'Adhesive': 8246,
         'Stick': 8242,
         'Essential': 8218,
         'Disposable': 8214,
         'Remover': 8140,
         'Best': 8100,
         'Mouse': 8098,
         'Max': 8064,
         'Resistant': 8032,
         'Brown': 8023,
         'Ages': 8022,
         'Thick': 7944,
         'Board': 7942,
         'Foot': 7927,
         'Remote': 7888,
         'Solid': 7870,
         'Workout': 7856,
         'Room': 7850,
         'Rubber': 7833,
         'Table': 7749,
         'Pants': 7721,
         'Play': 7703,
         'Pcs': 7670,
         'Strap': 7623,
         'Gaming': 7618,
         'Odor': 7616,
         'Yoga': 7608,
         'Feet': 7602,
         'Single': 7586,
         'Style': 7576,
         'Packs': 7558,
         'Keto': 7495,
         'Grade': 7490,
         'Ball': 7487,
         'Laundry': 7486,
         'Night': 7460,
         'Tablets': 7455,
         'Fine': 7454,
         'Handle': 7439,
         'Toddler': 7424,
         'Anti': 7406,
         'Cute': 7404,
         'Sensitive': 7385,
         'Wedding': 7385,
         'Safety': 7371,
         'Bar': 7367,
         'Durable': 7362,
         'Soap': 7356,
         'Ice': 7339,
         'Cats': 7317,
         'Milk': 7316,
         'Instant': 7278,
         'Wide': 7267,
         'Universal': 7261,
         'Magnetic': 7256,
         'Supplies': 7251,
         'Shirt': 7242,
         'Machine': 7239,
         'Plush': 7220,
         'Whole': 7217,
         'Quick': 7151,
         'Big': 7127,
         'Collection': 7123,
         'Inches': 7123,
         'Supply': 7113,
         'Butter': 7107,
         'Nylon': 7102,
         'Window': 7099,
         'Mesh': 7094,
         'Camera': 7080,
         'Watch': 7074,
         'Rolls': 7027,
         'Tops': 7018,
         'Tools': 7013,
         'Use': 7011,
         'Flat': 7007,
         'Tape': 6963,
         'Acid': 6954,
         'Comfort': 6941,
         'Strong': 6907,
         'Fire': 6870,
         'Family': 6868,
         'Treatment': 6857,
         'Tempered': 6823,
         'Belly': 6816,
         'Weight': 6815,
         'Band': 6795,
         'Life': 6789,
         'Shoes': 6776,
         'Wire': 6773,
         'Gray': 6746,
         'Grip': 6731,
         'Ink': 6723,
         'Wash': 6717,
         'Training': 6708,
         'Essentials': 6705,
         'Frame': 6699,
         'Cards': 6693,
         'Cheese': 6690,
         'Real': 6683,
         'Summer': 6670,
         'Edition': 6659,
         'Packaging': 6652,
         'Cold': 6634,
         'Tree': 6628,
         'Shelf': 6627,
         'Heat': 6624,
         'Pen': 6617,
         'Wooden': 6591,
         'Plug': 6571,
         'Aluminum': 6568,
         'Pockets': 6523,
         'Flavor': 6511,
         'Vinyl': 6494,
         'Shampoo': 6485,
         'Sleep': 6479,
         'Mix': 6477,
         'Sheet': 6468,
         'Purina': 6449,
         'Microfiber': 6441,
         'Treats': 6418,
         'Shoe': 6413,
         'Head': 6374,
         'Grey': 6368,
         'HDMI': 6346,
         'Beach': 6337,
         'Ounces': 6333,
         'Warm': 6321,
         'Formula': 6312,
         'Front': 6274,
         'Flavored': 6252,
         'Paint': 6243,
         'Alexa': 6232,
         'Craft': 6221,
         'Bra': 6201,
         'Mattress': 6183,
         'Display': 6182,
         'Headphones': 6171,
         'Tank': 6167,
         'Floor': 6143,
         'Shorts': 6142,
         'Micro': 6115,
         'Litter': 6079,
         'Touch': 6076,
         'Vacuum': 6070,
         'Sport': 6060,
         'Extension': 6046,
         'Type': 6019,
         'Stickers': 6006,
         'Mens': 6002,
         'Stretch': 5990,
         'Fleece': 5974,
         'Zero': 5967,
         'Dishwasher': 5959,
         'Chair': 5945,
         'Seat': 5932,
         'Star': 5924,
         'School': 5924,
         'Year': 5893,
         'iPad': 5883,
         'Clip': 5882,
         'Fits': 5878,
         'System': 5858,
         'Elastic': 5846,
         'Self': 5817,
         'Vintage': 5805,
         'Rechargeable': 5797,
         'Wipes': 5790,
         'Cap': 5777,
         'Halloween': 5768,
         'Candy': 5750,
         'Washable': 5733,
         'Pump': 5716,
         'Waist': 5708,
         'Bulk': 5705,
         'Bedroom': 5704,
         'Animal': 5702,
         'Bands': 5698,
         'Grain': 5694,
         'Fun': 5690,
         'Xbox': 5671,
         'Auto': 5668,
         'Acne': 5662,
         'Roll': 5656,
         'Slip': 5650,
         'One': 5646,
         'Lip': 5640,
         'Old': 5624,
         'Male': 5619,
         'Complete': 5615,
         'Curtain': 5611,
         'Heart': 5607,
         'Includes': 5598,
         'Sun': 5593,
         'Breathable': 5582,
         'Living': 5578,
         'Coconut': 5567,
         'Winter': 5539,
         'Value': 5537,
         'Beef': 5532,
         'Sweet': 5518,
         'Decoration': 5518,
         'Acrylic': 5496,
         'Bike': 5486,
         'Multi': 5440,
         'Side': 5423,
         'Cell': 5407,
         'Decorative': 5381,
         'Moisturizing': 5376,
         'Belt': 5339,
         'Blanket': 5322,
         'Basic': 5319,
         'Cool': 5317,
         'Matte': 5316,
         'Fish': 5280,
         'Running': 5277,
         'House': 5274,
         'Iron': 5274,
         'Crystal': 5273,
         'Loose': 5254,
         'Vitamins': 5246,
         'Repair': 5232,
         'Cups': 5212,
         'BPA': 5185,
         'Blend': 5174,
         'Cushion': 5160,
         'Print': 5160,
         'Bamboo': 5144,
         'Baking': 5130,
         'Work': 5128,
         'Square': 5123,
         'Spring': 5106,
         'Flower': 5104,
         'Drink': 5091,
         'Vanilla': 5084,
         'Floral': 5082,
         'Performance': 5057,
         'Covers': 5052,
         'Base': 5040,
         'Google': 5038,
         'Rose': 5033,
         'Clips': 5033,
         'Monitor': 5032,
         'Photo': 5000,
         'Orange': 4999,
         'Supports': 4994,
         'Fashion': 4990,
         'Thin': 4982,
         'Wrap': 4980,
         'Drive': 4960,
         'Tray': 4955,
         'Flexible': 4952,
         'Audio': 4941,
         'Bubble': 4931,
         'Clothes': 4927,
         'Friendly': 4927,
         'Rice': 4919,
         'Diamond': 4900,
         'Keyboard': 4874,
         'Rack': 4874,
         'Note': 4854,
         'Strip': 4841,
         'Hat': 4840,
         'Decorations': 4835,
         'Shoulder': 4827,
         'Muscle': 4812,
         'Lace': 4802,
         'First': 4794,
         'Tablet': 4773,
         'Lamp': 4771,
         'Your': 4767,
         'Cloth': 4742,
         'Hooks': 4733,
         'Holiday': 4729,
         'Designed': 4726,
         'Lid': 4724,
         'Shirts': 4719,
         'Necklace': 4712,
         'Fan': 4704,
         'Athletic': 4696,
         'Peanut': 4686,
         'Gloves': 4665,
         'Pencil': 4665,
         'inches': 4657,
         'Advanced': 4624,
         'Lotion': 4624,
         'Roast': 4620,
         'Funny': 4618,
         'Desktop': 4611,
         'Girl': 4601,
         'Compact': 4593,
         'Insulated': 4593,
         'Frozen': 4589,
         'Sea': 4588,
         'Yellow': 4573,
         'Snacks': 4569,
         'Trash': 4567,
         'Ground': 4560,
         'Camping': 4558,
         'Fluid': 4554,
         'Purple': 4548,
         'Total': 4547,
         'Works': 4538,
         'Gym': 4530,
         'Pressure': 4525,
         'Button': 4522,
         'Strips': 4512,
         'Pairs': 4511,
         'Conditioner': 4503,
         'Cut': 4501,
         'Lemon': 4494,
         'Guide': 4493,
         'Delivery': 4490,
         'Per': 4483,
         'Modern': 4476,
         'Salt': 4475,
         'Key': 4464,
         'Speed': 4453,
         'Dish': 4441,
         'Nails': 4431,
         'Dental': 4424,
         'Rings': 4424,
         'Deluxe': 4404,
         'Pouch': 4386,
         'Gallon': 4381,
         'Basket': 4379,
         'Wild': 4379,
         'Pound': 4375,
         'Queen': 4349,
         'Earrings': 4341,
         'Games': 4326,
         'Cooling': 4324,
         'Gentle': 4320,
         'Cans': 4320,
         'Bottles': 4309,
         'Exercise': 4292,
         'Printer': 4290,
         'Sound': 4286,
         'String': 4274,
         'Smooth': 4272,
         'Shockproof': 4245,
         'Meal': 4216,
         'Razor': 4209,
         'Sizes': 4206,
         'Wax': 4205,
         'Ultimate': 4201,
         'Stereo': 4191,
         'Lens': 4179,
         'Proof': 4178,
         'Ceramic': 4176,
         'Arm': 4162,
         'Knife': 4162,
         'Space': 4161,
         'Knit': 4159,
         'Furniture': 4137,
         'Blade': 4134,
         'Nose': 4125,
         'Unisex': 4114,
         'Refill': 4106,
         'Teeth': 4093,
         'Pot': 4080,
         'Charcoal': 4074,
         'Towel': 4073,
         'Fitness': 4069,
         'Lunch': 4051,
         'Video': 4045,
         'Dispenser': 4036,
         'Joint': 4033,
         'Lock': 4032,
         'Glasses': 4032,
         'MacBook': 4029,
         'Leggings': 4028,
         'Foldable': 4024,
         'Wallet': 4021,
         'Moisturizer': 4018,
         'Costume': 4012,
         'Twin': 4002,
         'Cooking': 3996,
         'Moisture': 3994,
         'Step': 3987,
         'Jack': 3980,
         'Mint': 3980,
         'Compression': 3979,
         'Regular': 3968,
         'Nutrition': 3966,
         'Noise': 3958,
         'Bowl': 3943,
         'Tall': 3942,
         'Maximum': 3928,
         'Comfortable': 3925,
         'Rainbow': 3914,
         'Polish': 3914,
         'Mega': 3909,
         'Sticks': 3906,
         'Children': 3905,
         'Soy': 3889,
         'Roller': 3883,
         'Sticker': 3857,
         'Fat': 3853,
         'PlayStation': 3852,
         'Thermal': 3851,
         'Stress': 3850,
         'Chain': 3846,
         'Vary': 3844,
         'Controller': 3842,
         'Quality': 3841,
         'Painting': 3833,
         'Test': 3831,
         'Tube': 3826,
         'Picture': 3826,
         'Ergonomic': 3822,
         'Container': 3816,
         'Building': 3813,
         'Servings': 3812,
         'Ideal': 3806,
         'Braided': 3790,
         'Fragrance': 3786,
         'Plan': 3784,
         'Crew': 3782,
         'Seal': 3775,
         'Candle': 3764,
         'Generation': 3762,
         'Aid': 3762,
         'Fiber': 3753,
         'Pool': 3750,
         'Wired': 3749,
         'Release': 3748,
         'Surface': 3742,
         'Hanes': 3740,
         'Honey': 3724,
         'Jar': 3722,
         'Tie': 3722,
         'Coloring': 3719,
         'Cake': 3710,
         'Removable': 3704,
         'Capacity': 3704,
         'Beauty': 3698,
         'Zinc': 3698,
         'Time': 3694,
         'Knee': 3684,
         'Microphone': 3683,
         'Pop': 3676,
         'Glitter': 3675,
         'Colorful': 3675,
         'Zipper': 3673,
         'Meat': 3666,
         'Cabinet': 3666,
         'Hook': 3661,
         'Lightning': 3659,
         'Lavender': 3658,
         'Underwear': 3645,
         'Crafts': 3639,
         'Android': 3638,
         'Collar': 3628,
         'Magic': 3619,
         'Puppy': 3616,
         'Breakfast': 3612,
         'Satin': 3604,
         'Open': 3600,
         'Personal': 3596,
         'LCD': 3595,
         'Containers': 3594,
         'Artificial': 3590,
         'Digestive': 3577,
         'Model': 3572,
         'WiFi': 3566,
         'Can': 3557,
         'Folding': 3550,
         'Bright': 3550,
         'Products': 3536,
         'Hose': 3526,
         'Throw': 3525,
         'Female': 3524,
         'Cleansing': 3519,
         'TPU': 3516,
         'Action': 3512,
         'Canvas': 3512,
         'Roasted': 3506,
         'Triple': 3503,
         'Mouth': 3502,
         'Pepper': 3500,
         'Toddlers': 3500,
         'Batteries': 3492,
         'Solar': 3491,
         'Active': 3481,
         'Down': 3481,
         'Ankle': 3468,
         'count': 3467,
         'Puzzle': 3467,
         'Film': 3462,
         'Handheld': 3462,
         'World': 3462,
         'Backpack': 3462,
         'Masks': 3454,
         'Scrub': 3452,
         'Glue': 3448,
         'Potato': 3443,
         'Off': 3439,
         'Years': 3424,
         'PCS': 3418,
         'Wrist': 3414,
         'Disney': 3414,
         'Luxury': 3408,
         'Little': 3393,
         'Bird': 3386,
         'Probiotics': 3379,
         'Dryer': 3374,
         'Length': 3371,
         'Silk': 3368,
         'Pets': 3365,
         'Edge': 3362,
         'Sets': 3354,
         'Guitar': 3344,
         'Stain': 3337,
         'Coat': 3337,
         'Starter': 3327,
         'Cleanser': 3322,
         'Hyaluronic': 3319,
         'Thermometer': 3302,
         'Drain': 3297,
         'Alkaline': 3290,
         'Patch': 3281,
         'Pan': 3279,
         'Headset': 3277,
         'Tip': 3276,
         'King': 3272,
         'Bumper': 3271,
         'Dust': 3269,
         'Anker': 3268,
         'Leg': 3258,
         'Carbon': 3252,
         'Maker': 3243,
         'Tub': 3243,
         'Diet': 3241,
         'Love': 3241,
         'Chew': 3241,
         'RGB': 3239,
         'Bracelet': 3236,
         'Toothbrush': 3235,
         'Bars': 3229,
         'Point': 3225,
         'Helps': 3217,
         'Extract': 3204,
         'Tips': 3200,
         'Cordless': 3198,
         'Trimmer': 3197,
         'Mirror': 3196,
         'Scale': 3195,
         'Genuine': 3183,
         'Sleeveless': 3178,

In [14]:
# find most common item sold
nouns_count_df = pd.DataFrame(list(nouns_count.items()), columns=['Word', 'Count'])
nouns_count_df = nouns_count_df.sort_values(by='Count', ascending=False)
nouns_count_df.to_csv('noun_counts.csv', index=False)
nouns_count_df.head(30)

           Word  Count
185        Pack  86249
65        Black  65305
106       Count  57772
557         Set  53579
155       Women  49854
184       Ounce  49240
808        Hair  42933
74         Gift  42417
5          Card  40799
487        Free  39532
448       White  39414
279         Dog  39117
59       Amazon  38509
915        Kids  38448
918         Cat  37872
171        Case  37738
484     Natural  34630
45          USB  34032
386        Soft  33421
146         Bag  32285
99        Water  30940
604        Baby  30818
83   Compatible  30282
732        Home  29339
496        Size  28873
120      iPhone  28314
43          Men  28222
390       Light  28150
25        Steel  28098
366        High  27035

In [16]:
# filter for most common item sold: USB and ensure its category is consistent
usb_df = df[df['Title'].str.contains("USB", case=False, na=False)]
category_counts = usb_df['Category'].value_counts().reset_index()
category_counts
usb_df = usb_df[usb_df['Category'].isin(["Electronics", "Computer & Accessories"])]
usb_df.to_csv('usb.csv', index=False)
usb_df

,Purchase Price Per Unit,Quantity,Title,ASIN/ISBN (Product Code),Category
5,10.99,1,Micro USB Cable Android Charger - Syncwire [2-...,B01GFB2E9M,Computer & Accessories
6,4.99,1,Amazon Basics USB 2.0 Charger Cable - A-Male t...,B00NH13S44,Computer & Accessories
17,26.77,1,Logitech M570 Wireless Trackball Mouse – Ergon...,B0043T7FXE,Computer & Accessories
26,139.99,1,"WD 8TB Elements Desktop External Hard Drive, U...",B07D5V2ZXD,Computer & Accessories
30,19.99,1,Anker Powerline II USB-C to USB-C 3.1 Gen 2 Ca...,B072JYDQ7N,Electronics
...,...,...,...,...,...
1391547,8.99,1,"JSAUX Micro USB Cable Android Charger, (2-Pack...",B07H91JTCD,Electronics
1391724,23.79,1,"Wireless Keyboard and Mouse, WisFox Full-Size ...",B088WV74FS,Computer & Accessories
1391918,21.99,1,"Anker Portable Charger, 313 Power Bank (PowerC...",B07QXV6N1B,Electronics
1391920,7.99,1,COSOOS 2 Short USB-C to iPhone Cables (10in/26...,B09CZ2KZ9P,Electronics
1392012,41.99,1,HD Webcam 1080P Streaming Web Camera with Micr...,B085WXGMWG,Electronics

In [17]:
# prepare data for analysis of historic sales

usb_df["Demand Indicator"] = usb_df.groupby('ASIN/ISBN (Product Code)')['Quantity'].transform('sum')

## Model

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# define features and targets
X = usb_df[['Quantity', 'Demand Indicator', "Category"]]  
y = usb_df['Purchase Price Per Unit']

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
# Define categorical and numerical features
categorical_features = X.select_dtypes(
   include=["object"]
).columns.tolist()

numerical_features = X.select_dtypes(
   include=["float64", "int64"]
).columns.tolist()

In [21]:
preprocessor = ColumnTransformer(
   transformers=[
       ("cat", OneHotEncoder(), categorical_features),
       ("num", StandardScaler(), numerical_features),
   ]
)

pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", GradientBoostingRegressor(random_state=42)),
    ]
)

In [22]:
# Perform 5-fold cross-validation
cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(f"Cross-Validation MAE: {-np.mean(cv_scores)}")

# Fit the model on the training data
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

Cross-Validation MAE: 21.58181645669986

In [23]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Test MAE: {mae}, Test RMSE: {rmse}")

Test MAE: 22.5596068955129, Test RMSE: 68.53113666889747

In [ ]:
results = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
results.to_csv("result/predictions.csv", index=False)